### ISSUE TITLE
patch apply error

### ISSUE THREAD

**Issue by qwertygoesbreak** [e666666/robloxWineBuildGuide#14]
This is what happens if I try to run the patch.
```
~/wine-tkg-git$ git apply roblox-wine-staging-v2.2.patch
error: patch failed: wine-tkg-git/customization.cfg:150
error: wine-tkg-git/customization.cfg: patch does not apply
```
I am running linux mint 20.3

**Comment by rolexlinux** [comment]
Yeah it seems that patch has some errors. You can use mine and I think you should have no errors.
`curl https://raw.githubusercontent.com/rolexlinux/robloxWineBuildGuide/main/roblox-wine-staging-v2.2.patch --output roblox-wine-staging-v2.2.patch`
`git apply roblox-wine-staging-v2.2.patch`

**Comment by rolexlinux** [comment]
give me a sec while i refork. The above link wont work yet

**Comment by rolexlinux** [comment]
Ok it should work i will do a pull request in a bit

**Comment by qwertygoesbreak** [comment]
ok thank you it run with no error now!
