### ISSUE TITLE
Doesn't install properly if you have other versions of wine installed

### ISSUE THREAD

**Issue by cheezymousehouse825** [e666666/robloxWineBuildGuide#3]
Please add a section to the guide where it tells you to uninstall wine on your machine before you proceed.
I am on arch linux and the wine version I forgot to uninstall beforehand was 6.16-1 on the arch repository.

**Comment by e666666** [comment]
This should do it: https://github.com/e666666/robloxWineBuildGuide/commit/4e1edee89727b9facf4b68e04a9690faabb49fab
Please close the issue if you think it fixes the issue.

**Comment by e666666** [comment]
I'll assume that fixed it, closing issue
