### ISSUE TITLE
While building on Gentoo, wine-tkg-git runs with no errors but nothing is built.

### ISSUE THREAD

**Issue by Nirbodha** [e666666/robloxWineBuildGuide#8]
![Screenshot from 2021-10-31 19-24-07](https://user-images.githubusercontent.com/81642303/139611547-e8494894-2ad8-4fc2-97d5-101c3d374354.png)
Last line is "exit clean done" by the way.

**Comment by Nirbodha** [comment]
This is my prepare.log also.
```sh
Cloning into bare repository 'wine-mirror-git'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into bare repository 'wine-staging-git'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
./non-makepkg-build.sh: line 128: cd: /home/anikc/Applications/Grapejuice/wine-tkg-git/wine-tkg-git/wine-staging-git: No such file or directory


```

**Comment by karimrir1** [comment]
Seems like the git protocol is blocked on you're network or you don't have the correct file permissions here, Or maybe it's the public key?, Also this is not a problem related to the build guide, Please go make an issue at https://github.com/Frogging-Family/wine-tkg-git

**Comment by Nirbodha** [comment]
... I'm stupid.

Many apologies. I'll send this issue over there.

Also, in case anyone's wondering, you can try to change the protocol from https:// to git:// if needed. That's what solved this particular issue for me. Even then, I still got some errors.

Thank you @karimrir1, and many apologies once again.
